version: '3'

services:
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - '8081:8081'
    environment:
      - CLOUD_NAME=phuc-company
      - API_KEY=838986499921257
      - API_SECRET=24nudYVIDiv2F03axjKBbYP_eHY
      - DOMAIN_CONNECTION=['https://trim-audio.herokuapp.com']
  mysql:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: $store
        ports:
            - $MYSQL_LOCAL_PORT:3306
