version: 2.1
jobs:
  Manual_Build:
    machine:
      image: ubuntu-1604:201903-01
  
    steps:
    
      - checkout
      - restore_cache:
          keys:
          - node

      - run:
          name: Check node version
          command: |
            node -v

      - run:
          name: build test
          command: |
            npm test
            
      - save_cache:
          paths:
            - node_modules
          key: node
orbs:
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb
workflows:
  build-tests:
    jobs:
      - Manual_Build:
          type: approval
          filters:
            branches:
              only: deploy
      